[network]
name = "testnet4"
node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "smoke lock patch infant observe obscure noise fury border summer border shy"
