[project]
name = "passportx"
description = "PassportX Achievement Passport Smart Contracts"
authors = ["PassportX Team"]
telemetry = false
cache_dir = "./.clarinet"

[contracts.badge-issuer-trait]
path = "traits/badge-issuer-trait.clar"
epoch = 2.5

[contracts.badge-reader-trait]
path = "traits/badge-reader-trait.clar"
epoch = 2.5

[contracts.passport-nft]
path = "passport-nft.clar"
epoch = 2.5

[contracts.badge-metadata]
path = "badge-metadata.clar"
epoch = 2.5

[contracts.badge-issuer]
path = "badge-issuer.clar"
epoch = 2.5
depends_on = ["badge-metadata", "passport-nft"]

[contracts.badge-reader]
path = "badge-reader.clar"
epoch = 2.5
depends_on = ["badge-metadata", "passport-nft"]

[contracts.community-manager]
path = "community-manager.clar"
epoch = 2.5

[contracts.access-control]
path = "access-control.clar"
epoch = 2.5

[contracts.passport-core]
path = "passport-core.clar"
epoch = 2.5
depends_on = ["badge-issuer", "badge-reader", "access-control"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false